//
// Created by yangyueji on 3/25/17.
//

#ifndef INFLUENCEMAXIMIZATIONGPU_GLOBALSETTINGS_H
#define INFLUENCEMAXIMIZATIONGPU_GLOBALSETTINGS_H

#define PROB_SCALE 100 //from 0.0 ~ 1.0 scale to this range
#define TOPK 100


#endif //INFLUENCEMAXIMIZATIONGPU_GLOBALSETTINGS_H
